### ISSUE TITLE
add new package seems does not check already installed

### ISSUE THREAD

**Issue by mckaygerhard** [OpenMediaVault-Plugin-Developers/openmediavault-apttool#6]
i susessfully install "x" package using apttool package.. 

the procedure is:

- install apttool plugin
- reload GUI
- go to services->apttool->search
- add using search "x" package (ex "X" as apache2-utils)
- then after add go to services->apttool->packages
- the selected package is on the list. click it to selected
- then click over the "tool" icon to install
- package installed. then reload the GUI
- go to services->apttool->packages..  the recently isntalled package is on the list
- hit over the "+" icon and add the same named package already installed
- error happened

**IMPORTANT NOTE: same happened no matter package is on the list or not.. if package is already installed by apt will raised this error too!**

![image](https://github.com/user-attachments/assets/7635f4c7-ada6-44ae-b4b1-309a9b13b60e)

ERROR

```
The configuration object 'conf.service.apttool' is not unique. An object with the property 'packagename' and value 'apache2-utils' already exists.

OMV\AssertException: The configuration object 'conf.service.apttool' is not unique. An object with the property 'packagename' and value 'apache2-utils' already exists. in /usr/share/php/openmediavault/config/database.inc:532
Stack trace:
#0 /usr/share/openmediavault/engined/rpc/apttool.inc(171): OMV\Config\Database->assertIsUnique()
#1 [internal function]: OMVRpcServiceAptTool->setPackage()
#2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(122): call_user_func_array()
#3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod()
#4 /usr/sbin/omv-engined(544): OMV\Rpc\Rpc::call()
#5 {main}
```

**Comment by ryecoaaron** [comment]
The error is correct.  In your screenshot, you have apache2-utils in your package list.  Then you try to add it again and it tells you it is not unique.  This is correct behavior.  Why would you want to add the same package again?

This error has nothing to do with its status in dpkg.  Packages in the Packages tab are just how you enter them in the OMV database so that the plugin can perform actions on that package.

**Comment by mckaygerhard** [comment]
i mean that apache2-utils could be not in the list and the error happened.. then the message mus be more descriptibe.. but ok .. 

i will close i just try to describe that a better check must be performed

**Comment by ryecoaaron** [comment]
The plugin is using the [built-in OMV function](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-apttool/blob/master/usr/share/openmediavault/engined/rpc/apttool.inc#L171) that detects duplicates.  It is used in just about every OMV plugin.  

This function provides the error message as well.  All I can think is that you double clicked on the Add button because you thought the first click did nothing.
